require("core.functions.open-in-finder")
require("core.functions.directory-index")
require("core.functions.open-in-yazi")
require("core.functions.word-templates")
require("core.functions.tex-to-docx")
require("core.functions.winbar").setup()
require("core.functions.bild-preview-mac")
require("core.functions.leader-leader-x-source-file")
require("core.functions.latex-comment-figures")
require("core.functions.latex-comment-figures-compile")
require("core.functions.latex-beamer-pdf-to-handout")
require("core.functions.latex-beamer-invisible")
require("core.functions.zotero-open-pdf")
require("core.functions.macro")
require("core.functions.jump-closing")
require("core.functions.oil-send-to-thunderbird")
-- require("core.functions.oil-copy-file-change-dir")
-- require("core.functions.oil-copy-file-change-dir-dracoon")
require("core.functions.oil-copy-file-fuzzy")
require("core.functions.oil-go-to-dir")
require("core.functions.oil-file-info")
require("core.functions.oil-project-work-gpt-template")
